ARG DOWNLOAD_IMAGE_NAME=golang:1.24.5-alpine
ARG BUILD_IMAGE_NAME=golang:1.24-bullseye
#ARG IMAGE_NAME=alpine
ARG IMAGE_NAME=debian:bullseye

FROM ${DOWNLOAD_IMAGE_NAME} AS packages_image
ENV PATH=/usr/local/go/bin:$PATH
WORKDIR /go/src
COPY go.mod go.sum ./
RUN echo "packages_image" && \
    go mod download

FROM ${BUILD_IMAGE_NAME} AS build_image
LABEL temporary=""
ARG BRANCH
ARG VERSION
ARG USERNAME
ARG USERPASSWD
ENV CGO_ENABLED=1
WORKDIR /go/
COPY --from=packages_image /go ./
#RUN echo -e "build_image" && \
#    rm -r ./src && \
#    apk update && \
#    apk add --no-cache git gcc musl-dev pkgconf librdkafka-dev
RUN echo -e "build_image" && \
    rm -r ./src && \
    apt-get update && \
    apt-get install -y git librdkafka-dev pkg-config && \
    # брать исходный код с репозитория на gitlab.cloud.gcm 
    #git clone -b ${BRANCH} http://${USERNAME}:${USERPASSWD}@gitlab.cloud.gcm/a.belyakov/placeholder_doc-basedb_bi.zone.git ./src/${VERSION}/ && \
    ##RUN git clone -b ${BRANCH} http://${USERNAME}:${USERPASSWD}@192.168.9.33/a.belyakov/placeholder-doc-basedb-bi-zone.git ./src/${VERSION}/ 
    #&& \
    #RUN git clone -b ${BRANCH} http://${USERNAME}:${USERPASSWD}@192.168.9.33/a.belyakov/placeholder-doc-basedb-bi-zone.git ./src/${VERSION}/ 
    #&& \
    # брать исходный код с репозитория на github.com 
    git clone -b ${BRANCH} https://github.com/av-belyakov/placeholder_doc-basedb_bi.zone.git  ./${VERSION}/ && \
    go build -C ./${VERSION}/cmd/ -o ../app

FROM ${IMAGE_NAME}
LABEL author="Artemij Belyakov"
# аргумент STATUS содержит режим запуска приложения prod или development
#если значение содержит запись development, то в таком режиме и будет
#работать приложение, во всех остальных случаях режим работы prod
ARG GROUP_ID=1500
ARG STATUS=""
ARG VERSION
ARG USERNAME=dockeruser
ARG US_DIR=/opt/placeholder_doc-basedb_bi.zone
ENV GO_PHDOCBASEDB_MAIN=${STATUS}
#RUN addgroup --g 1500 groupcontainer && \
#    adduser -u 1500 -G groupcontainer -D ${USERNAME} --home ${US_DIR}
RUN addgroup --gid ${GROUP_ID} groupcontainer 
#&& \
RUN useradd -u ${GROUP_ID} -G ${GROUP_ID} --home ${US_DIR} ${USERNAME} groupcontainer
USER ${USERNAME}
WORKDIR ${US_DIR}
RUN mkdir ./logs && \
    apt-get install -y git librdkafka-dev pkg-config 
COPY --from=build_image /go/src/${VERSION}/app ./
COPY --from=build_image /go/src/${VERSION}/README.md ./
COPY --from=build_image /go/src/${VERSION}/version ./ 
COPY config/* ./config/

ENTRYPOINT [ "./app" ]