NATS: # в основном используется для обогащения данных доп. информацией
  host: nats.cloud.gcm
  port: 4222
  cache_ttl: 3600
  subscriptions:
  enriching_queries:
    get_geoip_info: object.geoip-request
    get_sensor_info: object.sensor-info-request
KAFKA: # приём информации для её последующей обработки
  host: localhost
  port: 9092
  cache_ttl: 3600
  topics:
    alerts: alertmgr-alerts
    soar-alerts: soar-alertmgr-alerts-default-topic
DATABASESTORAGE: # хранилище принятой информации
  host: datahook.cloud.gcm
  port: 9200
  user: writer
  namedb: ""
  storage_name_db:
    alert: module_placeholderdb_alert
    case: module_placeholderdb_case
DATABASEWRITELOG: # хранилище логов работы модуля
  host: datahook.cloud.gcm
  port: 9200
  user: log_writer
  namedb: ""
  storage_name_db: placeholder_doc-base-db
