COMMONINFO:
  file_name: config_dev.yml
  regional_objects: gcm
NATS:
  host: 192.168.9.208
  port: 4222
  cache_ttl: 3600
  subscriptions:
  enriching_queries:
    get_geoip_info: object.geoip-request.test
    get_sensor_info: object.sensor-info-request.test
KAFKA:
  host: localhost
  port: 9092
  cache_ttl: 3600
  topics:
    alerts: object.topicalerttype.test
    soar-alerts: object.topicsoaralertstype.test
DATABASESTORAGE:
  host: 192.168.9.208
  port: 9200
  user: placeholder-docbase-db
  namedb: ""
  storage_name_db:
    alert: test.module_placeholderdb_alert
    case: test.module_placeholderdb_case
DATABASEWRITELOG:
  host: 192.168.9.208
  port: 9200
  user: placeholder-docbase-db
  namedb: ""
  storage_name_db: placeholder_doc-base-db
