COMMONINFO:
  file_name: config_dev.yml
  regional_object: gcm-dev
NATS:
  host: 192.168.9.208
  port: 4222
  cache_ttl: 3600
  subscriptions:
  enriching_queries:
    get_geoip_info: object.geoip-request.test
    get_sensor_info: object.sensor-info-request.test
KAFKA:
  host: 192.168.9.71
  port: 31792
  cache_ttl: 3600
  topics:
    alerts: alertmgr-alerts
    soar-alerts: soar-alertmgr-alerts-default-topic
DATABASESTORAGE:
  host: 192.168.9.208
  port: 9200
  user: placeholder-docbase-db
  namedb: ""
  storage_name_db:
    alerts: module_placeholderdb_bizone_alerts
    soar-alerts: module_placeholderdb_bizone_soar-alerts
DATABASEWRITELOG:
  host: 192.168.9.208
  port: 9200
  user: placeholder-docbase-db
  namedb: ""
  storage_name_db: placeholder_doc-base-db
