COMMONINFO:
  file_name: config_prod.yml
  regional_object: gcm-prod
NATS: # в основном используется для обогащения данных доп. информацией
  host: nats.cloud.gcm
  port: 4222
  cache_ttl: 3600
  subscriptions:
    some: somesubscription
  enriching_queries:
    get_geoip_info: object.geoip-request
    get_sensor_info: object.sensor-info-request
KAFKA: # приём информации для её последующей обработки
  host: 192.168.9.71
  port: 31792
  cache_ttl: 3600
  topics:
    alerts: alertmgr-alerts
    cases: socd-soar-prod-issue-v1
DATABASESTORAGE: # хранилище принятой информации
  host: datahook.cloud.gcm
  port: 9200
  user: writer
  namedb: ""
  storage_name_db:
    alerts: module_placeholderdb_bizone_alerts
    case: module_placeholderdb_bizone_case
DATABASEWRITELOG: # хранилище логов работы модуля
  host: datahook.cloud.gcm
  port: 9200
  user: log_writer
  namedb: ""
  storage_name_db: module_placeholderdb_bizone
